package com.example.poc.graphhopper.model;

public enum MismatchReason {
	NO_WAY_NODE_SEQUENCE,
	NO_DB_CANDIDATE_FOR_WAY,
	AMBIGUOUS_ENDPOINT_CANDIDATE,
	ENDPOINT_MATCH_GEOMETRY_DIFFERENT,
	WAY_NODE_REPEAT_NOT_ANCHOR,
	GRAPHHOPPER_SPLIT_EXTRA,
	DB_SPLIT_EXTRA
}
